# Generated by Django 4.2.7 on 2024-02-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
    ]
