# Generated by Django 4.2.7 on 2024-02-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_rename_email_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
